POST http://localhost:300/quotes/ HTTP/1.1
content-type: application/json

{
    "user": "bob_leponge21",
    "quote": "Absolument"
}

###
Delete http://localhost:300/quotes/ HTTP/1.1
content-type: application/json

{
    "_id": "63c8292991c362577bc86322"
}
###
Post http://localhost:300/users/ HTTP/1.1
content-type: application/json

{
    "email": "bobLepong@outlook.com",
    "userName": "bob_leponge21",
    "password": "edgyMan 27"
}
