POST http://localhost:300/quotes/ HTTP/1.1
content-type: application/json

{
    "user": "Kelvin Chen",
    "quote": "heeheee"
}

###
Post http://localhost:300/quotes/delete/ HTTP/1.1
content-type: application/json

{
    "_id": "63c82f806b8edd7533f5deb7"
}

###
Post http://localhost:300/users/ HTTP/1.1
content-type: application/json

{
    "email": "bobLepong@outlook.com",
    "userName": "Kelvin Chen",
    "password": "edgyMan 27"
}
