POST http://localhost:300/quotes/ HTTP/1.1
content-type: application/json

{
    "user": "Kelvin Chen",
    "quote": "Money is awesome"
}

###
Post http://localhost:300/quotes/delete/ HTTP/1.1
content-type: application/json

{
    "_id": "63c8139d9f29732b9b68eba4"
}

###
Post http://localhost:300/users/delete/ HTTP/1.1
content-type: application/json

{
    "userName": "bob_leponge21"
}

###
Post http://localhost:300/users/ HTTP/1.1
content-type: application/json

{
    "email": "kelvin@outlook.com",
    "userName": "Kelvin Chen",
    "password": "tehee"
}

###
Post http://localhost:300/users/login/ HTTP/1.1
content-type: application/json

{
    "userName": "Kelvin Chen",
    "password": "edgyMan 27"
}

###
Post http://localhost:300/users/posts/ HTTP/1.1
content-type: application/json

{
    "userName": "Kelvin Chen"
}
###
Post http://localhost:300/users/delete/ HTTP/1.1
content-type: application/json

{
    "userName": "Kelvin Chen"
}
